export const assets = {
  logo: "/assets/logo.svg",
  logoVote: "/assets/logo-vote.svg",
  logoPath1: "/assets/logo-path1.svg",
  logoV: "/assets/logo-v.svg",
  logoPath2: "/assets/logo-path2.svg",
  searchIcon: "/assets/search-icon.svg",
  arrowForward: "/assets/arrow-forward.svg",
  arrowForwardDark: "/assets/arrow-forward-dark.svg",
  chevronRight: "/assets/chevron-right.svg",
  chevronDown: "/assets/chevron-down.svg",
  multipleStop: "/assets/multiple-stop.svg",
  checkGreen: "/assets/check-green.svg",
  checkWhite: "/assets/check-white.svg",
  xIcon: "/assets/x-icon.svg",
  iosShare: "/assets/ios-share.svg",
  callMade: "/assets/call-made.svg",
  emailIcon: "/assets/email-icon.svg",
  xLogo: "/assets/x-logo.svg",
  symbolLogo: "/assets/symbol-logo.svg",
  layerIcon: "/assets/layer-icon.svg",
  lineDiv: "/assets/line-div.svg",
  keyboardArrowDown: "/assets/keyboard-arrow-down.svg",

  // Candidate photos (pravatar.cc — consistent by img ID)
  johnCornyn: "https://i.pravatar.cc/256?img=60",
  colinAllred: "https://i.pravatar.cc/256?img=33",
  rolandGutierrez: "https://i.pravatar.cc/256?img=12",
  justinNelson: "https://i.pravatar.cc/256?img=7",
  kayGranger: "https://i.pravatar.cc/256?img=44",
  craigGoldman: "https://i.pravatar.cc/256?img=51",
  janeHamilton: "https://i.pravatar.cc/256?img=20",
  trevinoMartinez: "https://i.pravatar.cc/256?img=14",
  gregAbbott: "https://i.pravatar.cc/256?img=52",
  betoORourke: "https://i.pravatar.cc/256?img=11",
  imelda_reyes: "https://i.pravatar.cc/256?img=23",
  markCuban: "https://i.pravatar.cc/256?img=53",
  danPatrick: "https://i.pravatar.cc/256?img=59",
  mikeCollier: "https://i.pravatar.cc/256?img=8",
  deannaLuna: "https://i.pravatar.cc/256?img=45",
  mattieParker: "https://i.pravatar.cc/256?img=24",
  carlosFlores: "https://i.pravatar.cc/256?img=15",
  debJohnson: "https://i.pravatar.cc/256?img=47",
  leonardFirestone: "https://i.pravatar.cc/256?img=57",
  christinaReyes: "https://i.pravatar.cc/256?img=26",
  jaredWilliams: "https://i.pravatar.cc/256?img=6",
  patriciaDavis: "https://i.pravatar.cc/256?img=48",
  natalieRuiz: "https://i.pravatar.cc/256?img=25",
  michaelWashington: "https://i.pravatar.cc/256?img=18",
  andreaHarrison: "https://i.pravatar.cc/256?img=32",

  // Endorser avatars (pravatar.cc — consistent by img ID)
  endorser1: "https://i.pravatar.cc/96?img=36",
  endorser2: "https://i.pravatar.cc/96?img=37",
  endorser3: "https://i.pravatar.cc/96?img=38",
  endorser4: "https://i.pravatar.cc/96?img=39",
  endorser5: "https://i.pravatar.cc/96?img=40",
  endorser6: "https://i.pravatar.cc/96?img=41",
  endorser7: "https://i.pravatar.cc/96?img=42",
  endorser8: "https://i.pravatar.cc/96?img=43",
  endorser9: "https://i.pravatar.cc/96?img=49",
  endorser10: "https://i.pravatar.cc/96?img=50",
  endorser11: "https://i.pravatar.cc/96?img=54",
  endorser12: "https://i.pravatar.cc/96?img=55",
  endorser13: "https://i.pravatar.cc/96?img=56",
  endorser14: "https://i.pravatar.cc/96?img=58",
  endorser15: "https://i.pravatar.cc/96?img=61",

  // Source logos
  logo1: "/assets/source-logo1.png",
  logo2: "/assets/source-logo2.png",
  logo3: "/assets/source-logo3.png",
  logo4: "/assets/source-logo4.png",
  logo5: "/assets/source-logo5.png",

  // City/CTA images
  fortWorth: "/assets/fort-worth.png",
  ctaPinLeft: "/assets/cta-pin-left.png",
  ctaPinRight: "/assets/cta-pin-right.png",
  sharePreview: "/assets/share-preview.png",
  sharePreview2: "/assets/share-preview2.png",
  votingBooth: "/assets/voting-booth.png",
  iVotedStickers: "/assets/i-voted-stickers.png",

  // Voter guide avatars
  danielJoffe: "https://i.pravatar.cc/96?img=62",
  hobokenGirl: "https://i.pravatar.cc/96?img=63",
  voterMike: "https://i.pravatar.cc/96?img=64",

  // Voter guide covers (desktop)
  guideCover1: "/assets/guide-cover-1.png",
  guideCover2: "/assets/guide-cover-2.png",
  guideCover3: "/assets/guide-cover-3.png",

  // Share preview (desktop)
  sharePreviewDesktop: "/assets/share-preview-desktop.png",
} as const;
