export const assets = {
  logo: "/assets/logo.svg",
  logoVote: "/assets/logo-vote.svg",
  logoPath1: "/assets/logo-path1.svg",
  logoV: "/assets/logo-v.svg",
  logoPath2: "/assets/logo-path2.svg",
  searchIcon: "/assets/search-icon.svg",
  arrowForward: "/assets/arrow-forward.svg",
  arrowForwardDark: "/assets/arrow-forward-dark.svg",
  chevronRight: "/assets/chevron-right.svg",
  chevronDown: "/assets/chevron-down.svg",
  multipleStop: "/assets/multiple-stop.svg",
  checkGreen: "/assets/check-green.svg",
  checkWhite: "/assets/check-white.svg",
  xIcon: "/assets/x-icon.svg",
  iosShare: "/assets/ios-share.svg",
  callMade: "/assets/call-made.svg",
  emailIcon: "/assets/email-icon.svg",
  xLogo: "/assets/x-logo.svg",
  symbolLogo: "/assets/symbol-logo.svg",
  layerIcon: "/assets/layer-icon.svg",
  lineDiv: "/assets/line-div.svg",
  keyboardArrowDown: "/assets/keyboard-arrow-down.svg",

  // Candidate photos
  johnCornyn: "/assets/john-cornyn.png",
  jamesSolomon: "/assets/james-solomon.png",
  billOdea: "/assets/bill-odea.png",
  craigGoldman: "/assets/craig-goldman.png",
  patrickAmbrossi: "/assets/patrick-ambrossi.png",
  catherineHealy: "/assets/catherine-healy.png",
  gregAbbott: "/assets/john-cornyn.png",
  danPatrick: "/assets/craig-goldman.png",
  mussabAli: "/assets/mussab-ali.png",
  jeffWilliams: "/assets/jeff-williams.png",
  nataliaIoffe: "/assets/natalia-ioffe.png",
  ahmedKheir: "/assets/ahmed-kheir.png",
  melanyCruz: "/assets/melany-cruz.png",

  // Endorser avatars
  endorser1: "/assets/endorser1.png",
  endorser2: "/assets/endorser2.png",
  endorser3: "/assets/endorser3.png",
  endorser4: "/assets/endorser4.png",
  endorser5: "/assets/endorser5.png",
  endorser6: "/assets/endorser6.png",
  endorser7: "/assets/endorser7.png",
  endorser8: "/assets/endorser8.png",
  endorser9: "/assets/endorser9.png",
  endorser10: "/assets/endorser10.png",
  endorserJoyce: "/assets/endorser6.png",
  endorserDistrict: "/assets/endorser-district.png",
  endorserFW: "/assets/endorser-fw.png",

  // Source logos
  logo1: "/assets/source-logo1.png",
  logo2: "/assets/source-logo2.png",
  logo3: "/assets/source-logo3.png",
  logo4: "/assets/source-logo4.png",
  logo5: "/assets/source-logo5.png",

  // City/CTA images
  fortWorth: "/assets/fort-worth.png",
  ctaPinLeft: "/assets/cta-pin-left.png",
  ctaPinRight: "/assets/cta-pin-right.png",
  sharePreview: "/assets/share-preview.png",
  sharePreview2: "/assets/share-preview2.png",
  votingBooth: "/assets/voting-booth.png",
  iVotedStickers: "/assets/i-voted-stickers.png",

  // Voter guide avatars
  danielJoffe: "/assets/daniel-joffe.png",
  hobokenGirl: "/assets/hoboken-girl.png",
  voterMike: "/assets/voter-mike.png",
} as const;
