export const assets = {
  logo: "/assets/logo.svg",
  logoVote: "/assets/logo-vote.svg",
  logoPath1: "/assets/logo-path1.svg",
  logoV: "/assets/logo-v.svg",
  logoPath2: "/assets/logo-path2.svg",
  searchIcon: "/assets/search-icon.svg",
  arrowForward: "/assets/arrow-forward.svg",
  arrowForwardDark: "/assets/arrow-forward-dark.svg",
  chevronRight: "/assets/chevron-right.svg",
  chevronDown: "/assets/chevron-down.svg",
  multipleStop: "/assets/multiple-stop.svg",
  checkGreen: "/assets/check-green.svg",
  checkWhite: "/assets/check-white.svg",
  xIcon: "/assets/x-icon.svg",
  iosShare: "/assets/ios-share.svg",
  callMade: "/assets/call-made.svg",
  emailIcon: "/assets/email-icon.svg",
  xLogo: "/assets/x-logo.svg",
  symbolLogo: "/assets/symbol-logo.svg",
  layerIcon: "/assets/layer-icon.svg",
  allPrimariesIcon: "/assets/all-primaries-icon.svg",
  democraticPartyIcon: "/assets/democratic-party-icon.svg",
  republicanPartyIcon: "/assets/republican-party-icon.svg",
  lineDiv: "/assets/line-div.svg",
  keyboardArrowDown: "/assets/keyboard-arrow-down.svg",

  // Candidate photos (UIfaces AI-generated avatars)
  johnCornyn: "https://mockmind-api.uifaces.co/content/human/1.jpg",
  colinAllred: "https://mockmind-api.uifaces.co/content/human/2.jpg",
  rolandGutierrez: "https://mockmind-api.uifaces.co/content/human/3.jpg",
  justinNelson: "https://mockmind-api.uifaces.co/content/human/4.jpg",
  kayGranger: "https://mockmind-api.uifaces.co/content/human/5.jpg",
  craigGoldman: "https://mockmind-api.uifaces.co/content/human/6.jpg",
  janeHamilton: "https://mockmind-api.uifaces.co/content/human/7.jpg",
  trevinoMartinez: "https://mockmind-api.uifaces.co/content/human/8.jpg",
  gregAbbott: "https://mockmind-api.uifaces.co/content/human/9.jpg",
  betoORourke: "https://mockmind-api.uifaces.co/content/human/10.jpg",
  imelda_reyes: "https://mockmind-api.uifaces.co/content/human/11.jpg",
  markCuban: "https://mockmind-api.uifaces.co/content/human/12.jpg",
  danPatrick: "https://mockmind-api.uifaces.co/content/human/13.jpg",
  mikeCollier: "https://mockmind-api.uifaces.co/content/human/14.jpg",
  deannaLuna: "https://mockmind-api.uifaces.co/content/human/15.jpg",
  mattieParker: "https://mockmind-api.uifaces.co/content/human/16.jpg",
  carlosFlores: "https://mockmind-api.uifaces.co/content/human/17.jpg",
  debJohnson: "https://mockmind-api.uifaces.co/content/human/18.jpg",
  leonardFirestone: "https://mockmind-api.uifaces.co/content/human/19.jpg",
  christinaReyes: "https://mockmind-api.uifaces.co/content/human/20.jpg",
  jaredWilliams: "https://mockmind-api.uifaces.co/content/human/21.jpg",
  patriciaDavis: "https://mockmind-api.uifaces.co/content/human/22.jpg",
  natalieRuiz: "https://mockmind-api.uifaces.co/content/human/23.jpg",
  michaelWashington: "https://mockmind-api.uifaces.co/content/human/24.jpg",
  andreaHarrison: "https://mockmind-api.uifaces.co/content/human/25.jpg",

  // Additional candidates for expanded races
  samuelChen: "https://mockmind-api.uifaces.co/content/human/26.jpg",
  rebeccaThompson: "https://mockmind-api.uifaces.co/content/human/27.jpg",
  marcusJohnson: "https://mockmind-api.uifaces.co/content/human/28.jpg",
  elenaVargas: "https://mockmind-api.uifaces.co/content/human/29.jpg",
  davidMorales: "https://mockmind-api.uifaces.co/content/human/30.jpg",
  sarahPatel: "https://mockmind-api.uifaces.co/content/human/31.jpg",
  jamesWhitfield: "https://mockmind-api.uifaces.co/content/human/32.jpg",
  lisaNguyen: "https://mockmind-api.uifaces.co/content/human/33.jpg",
  robertTaylor: "https://mockmind-api.uifaces.co/content/human/34.jpg",
  angelaMitchell: "https://mockmind-api.uifaces.co/content/human/35.jpg",

  // Endorser avatars (UIfaces AI-generated avatars)
  endorser1: "https://mockmind-api.uifaces.co/content/human/101.jpg",
  endorser2: "https://mockmind-api.uifaces.co/content/human/102.jpg",
  endorser3: "https://mockmind-api.uifaces.co/content/human/103.jpg",
  endorser4: "https://mockmind-api.uifaces.co/content/human/104.jpg",
  endorser5: "https://mockmind-api.uifaces.co/content/human/105.jpg",
  endorser6: "https://mockmind-api.uifaces.co/content/human/106.jpg",
  endorser7: "https://mockmind-api.uifaces.co/content/human/107.jpg",
  endorser8: "https://mockmind-api.uifaces.co/content/human/108.jpg",
  endorser9: "https://mockmind-api.uifaces.co/content/human/109.jpg",
  endorser10: "https://mockmind-api.uifaces.co/content/human/110.jpg",
  endorser11: "https://mockmind-api.uifaces.co/content/human/111.jpg",
  endorser12: "https://mockmind-api.uifaces.co/content/human/112.jpg",
  endorser13: "https://mockmind-api.uifaces.co/content/human/113.jpg",
  endorser14: "https://mockmind-api.uifaces.co/content/human/114.jpg",
  endorser15: "https://mockmind-api.uifaces.co/content/human/115.jpg",
  endorser16: "https://mockmind-api.uifaces.co/content/human/116.jpg",
  endorser17: "https://mockmind-api.uifaces.co/content/human/117.jpg",
  endorser18: "https://mockmind-api.uifaces.co/content/human/118.jpg",
  endorser19: "https://mockmind-api.uifaces.co/content/human/119.jpg",
  endorser20: "https://mockmind-api.uifaces.co/content/human/120.jpg",

  // Source logos
  logo1: "/assets/source-logo1.png",
  logo2: "/assets/source-logo2.png",
  logo3: "/assets/source-logo3.png",
  logo4: "/assets/source-logo4.png",
  logo5: "/assets/source-logo5.png",

  // City/CTA images
  fortWorth: "/assets/fort-worth.png",
  ctaPinLeft: "/assets/cta-pin-left.png",
  ctaPinRight: "/assets/cta-pin-right.png",
  sharePreview: "/assets/share-preview.png",
  sharePreview2: "/assets/share-preview2.png",
  votingBooth: "/assets/voting-booth.png",
  iVotedStickers: "/assets/i-voted-stickers.png",

  // Voter guide avatars (UIfaces)
  danielJoffe: "https://mockmind-api.uifaces.co/content/human/130.jpg",
  hobokenGirl: "https://mockmind-api.uifaces.co/content/human/131.jpg",
  voterMike: "https://mockmind-api.uifaces.co/content/human/132.jpg",

  // Voter guide covers (desktop)
  guideCover1: "/assets/guide-cover-1.png",
  guideCover2: "/assets/guide-cover-2.png",
  guideCover3: "/assets/guide-cover-3.png",

  // Share preview (desktop)
  sharePreviewDesktop: "/assets/share-preview-desktop.png",
} as const;
